config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # get "fullcalendar", to: "pages#fullcalendar"
  get "calendar", to: "time_slots#calendar"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :time_slots, only: [:show, :index, :create, :update, :edit, :destroy] do
    resources :bookings, only: [:new, :create, :show]
    put :update_times, on: :member
  end

  resources :bookings, only: [:update]

  resources :users, only: [:user_profile] do
    resources :sport_classes, only: [:show, :new, :create, :index]
  end

  get "clients", to: "users#user_clients", as: "user_clients"
  get "clients/:id", to: "users#client_profile", as: "client_profile"

  resources :sport_classes
end

app/views/shared/_badge_booking_payment.html.erb
<div class="badge-booking-payment" data-booking-id="<%= booking.id %>">
  <% if booking.payment_received? %>
    <div class="item-timeslot-details">
      <%= link_to "Payé",booking_path(booking, choice: false), remote: true, method: :put, data: { confirm: "Êtes vous sûr(e) de passer le statut du paiement en impayé?"}, class:"payé" %>
    </div>
  <% else %>
    <div class="item-timeslot-details">
      <%= link_to "Impayé",booking_path(booking, choice: true), remote: true, method: :put, data: { confirm: "Êtes vous sûr(e) de passer le statut du paiement en payé?"}, class:"impayé" %>
    </div>
  <% end %>
</div>

app/views/shared/_client_due_payments.html.erb
<div class="paiement-card-impayes-show">
  <h6>Montant restant à payer par ce client </h6>
  <h4> <%= @bookings.where(payment_received: false).select {|b| b.time_slot.sport_class.coach_id == current_user.id}.map(&:time_slot).sum(&:price).round(0) %>€</h4>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_global_due_payments.html.erb
<div class="paiement-card-impayes-home">
  <div  data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample"> </a>
    <h6>Solde des paiements à recevoir</h6>
    <h4> <%= @unpaid_ca.round(0) %>€</h4>
  </div>
  <div class="collapse unpaid" id="collapseExample">
    <% @unpaid_client.uniq.each do |c| %>
      <%= link_to client_profile_path(c), class: 'd-flex justify-content-between' do %>
        <span>
          <%= "#{c.first_name} #{c.last_name}"%>
        </span>
        <span>
          <%= c.client_bookings.where(payment_received: false).select {|b| b.time_slot.sport_class.coach_id == current_user.id}.map(&:time_slot).sum(&:price).round(0) %>€
        </span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
<div class="logo">
  <%= link_to do %>
  <%= image_tag("Coacheo.png") %>
  <% end %>
</div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <a class="navbar-brand" href="#">
    <img src="https://avatars.githubusercontent.com/u/90185095?v=4"class="avatar-large" />
</a>
        <li class="nav-item dropdown">
          <h4 class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true"><%= current_user.first_name %></h4>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>