config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # get "fullcalendar", to: "pages#fullcalendar"
  get "calendar", to: "time_slots#calendar"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :time_slots, only: [:show, :index, :create, :update, :edit, :destroy] do
    resources :bookings, only: [:new, :create, :show]
    put :update_times, on: :member
  end

  resources :bookings, only: [:update]

  resources :users, only: [:user_profile] do
    resources :sport_classes, only: [:show, :new, :create, :index]
  end

  get "clients", to: "users#user_clients", as: "user_clients"
  get "clients/:id", to: "users#client_profile", as: "client_profile"

  resources :sport_classes
end

app/controllers/sport_classes_controller.rb
class SportClassesController < ApplicationController

# skip_before_action :authenticate_user!, only: [:index, :show]

  def index
  @sport_classes = current_user.sport_classes.order(category: :asc)
  end

  def show
  @sport_class = current_user.sport_classes.find_by_id(params[:id])

   if @sport_class
    else
      redirect_to sport_classes_path
    end
  end

  def new
    @sport_class = SportClass.new
  end

  def create
  @sport_class = SportClass.new(sport_class_params)
    if @sport_class.save
      redirect_to sport_classes_path
    else
      render :new
    end
  end

  def edit
    @sport_class = SportClass.find(params[:id])
  end

  def update
    @sport_class = SportClass.find(params[:id])
    @sport_class.update(sport_class_params)
    redirect_to sport_classes_path
  end

  def destroy
    @sport_class = SportClass.find(params[:id])
    if @sport_class.time_slots.any?
      flash[:alert] = "Ce cours a été réservé. Il ne peut donc pas être supprimé."
    else
      @sport_class.destroy
    end
      redirect_to sport_classes_path
  end

  private

  def sport_class_params
    params.require(:sport_class).permit(:name, :description, :category, :coach_id, :level, :group_size, :price, :duration, :address1, :address2, :post_code, :town)
  end

end

app/views/sport_classes/edit.html.erb
<div id="container">
  <%= link_to '', sport_classes_path, class:"fas fa-arrow-circle-left" %>

  <div class="container_registration">
    <h2>Cours de sport</h2>
    <%= simple_form_for(@sport_class) do |f| %>
      <div class="form-group1">
        <%= f.input :category , :prompt => "Discipline",  label: false, collection: (SportClass::SPORT_CATEGORY).keys.map(&:to_s)%>
        <%= f.input :name,label: false, placeholder: 'Intitulé'  %>
      </div>
        <%= f.input :description, label: false, placeholder: 'Description' %>
      <div class="form-group2">
        <%= f.input :duration, type:"time", label: false, collection:[15,30,45,60,75,90,120,150] %>
            <p>Durée en minutes</p>
      </div>
        <%= f.input :level,
                    label: "Niveau",
                    as: :radio_buttons,
                    input_html: { class: "tag-selector" },
                    item_wrapper_class: 'tag-item',
                    collection: SportClass::LEVELS%>
      <div class="form-group1">
        <%= f.input :group_size,label: false, label: 'Type de groupe',
                    as: :radio_buttons,
                    input_html: { class: "tag-selector" },
                    item_wrapper_class: 'tag-item',
                    collection: ['Individuel', 'Collectif'] %>
        <%= f.input :group_size,label: false, placeholder: "Nb de participants", value: '1', input_html: { type: 'number' }%>
      </div>
        <%= f.input :price, label: false, placeholder: 'Prix du cours par personne                                                                                    €' %>
        <%= f.input :address1, label: false, placeholder: 'Adresse' %>
      <div class="form-group1">
          <%= f.input :post_code, label: false, placeholder: 'Code postal' %>
          <%= f.input :town, label: false, placeholder: 'Ville' %>
      </div>
        <%= f.hidden_field :coach_id,  :value => current_user.id %>

      <div class="button2">
          <%= f.button :submit, value: "Mettre à jour le cours", label: 'Enregistrer' %>
      </div>
    <% end %>
  </div>
</div>

app/views/sport_classes/index.html.erb
  <div class="top_barre">
  <h1 class="catalogue">Catalogue des cours de sport</h1>
  <%= link_to 'Ajouter un cours de sport', new_sport_class_path, class: "button1" %>
  </div>

  <div class="cards-grid" >
    <% @sport_classes.each do |sport_class| %>
      <div class="card-index">
          <div class="card-corps">

            <div  class="blank-background" id="blank">
              <%= link_to sport_class_path(sport_class) do %>
              <h4 class="card-title-index"><%= sport_class.category %></h4>
            <div class="card-body-index">
            <h6 class="card-text" id="sport_class_name"> <%= sport_class.name %></h6>
            <p class="card-text" id="level"><em><%= sport_class.level %></em></p>
            </div>
            </div>
              <div class="card-title-image">
              <%= image_tag((SportClass::SPORT_CATEGORY)[sport_class.category.to_sym])%>
              </div>
            <div class="infos">
              <p><i class="fas fa-user-friends"></i><%= sport_class.group_size %></p>
              <p><i class="fas fa-clock"></i> <%= sport_class.duration %></p>
              <p><i class="fas fa-euro-sign"></i><%= sport_class.price.to_i %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/sport_classes/new.html.erb
<div id="container">
  <%= link_to '', sport_classes_path, class:"fas fa-arrow-circle-left" %>
  <div class="container_registration">
  <h2>Cours de sport</h2>
    <%= simple_form_for(@sport_class) do |f| %>
    <div class="form-group1">
      <%= f.input :category, :prompt => "Discipline",  label: false, collection: (SportClass::SPORT_CATEGORY).keys.map(&:to_s)%>
      <%= f.input :name,label: false, placeholder: 'Nom du cours'  %>
      </div>
      <%= f.input :description, label: false, placeholder: 'Description' %>
          <div class="form-group2">
      <%= f.input :duration, type:"time", label: false, collection:[15,30,45,60,75,90,120,150] %>
          <p>Durée en minutes</p>
      </div>
      <%= f.input :level,
                  label: "Niveau",
                  as: :radio_buttons,
                  input_html: { class: "tag-selector" },
                  item_wrapper_class: 'tag-item',
                  collection: SportClass::LEVELS%>
      <div class="form-group1" id="toggleType">
      <%= f.input :group_size,label: false, label: 'Type de cours',
                  as: :radio_buttons,
                  input_html: { class: "tag-selector" },
                  item_wrapper_class: 'tag-item',
                  collection: ['Individuel', 'Collectif'] %>
      </div>
      <%= f.input :group_size,label: false, placeholder: "Nb de participants", as: :hidden,  input_html: { value: 1 } %>
      <%= f.input :price, label: false, placeholder: 'Prix du cours par personne                                                                                   €' %>
      <%= f.input :address1, label: false, placeholder: 'Adresse' %>
      <div class="form-group1">
        <%= f.input :post_code, label: false, placeholder: 'Code postal' %>
        <%= f.input :town, label: false, placeholder: 'Ville' %>
      </div>
      <%= f.hidden_field :coach_id,  :value => current_user.id %>

      <div class="button2">
        <%= f.button :submit, value: "Enregistrer", label: 'Enregistrer' %>
      </div>
    <% end %>
  </div>
</div>

app/views/sport_classes/show.html.erb
<div class="show-sport-class">
  <%= link_to '', sport_classes_path, class:"fas fa-arrow-circle-left" %>
  <div class="card-sport" >
    <div class="cards-grid-show">
              <%= image_tag((SportClass::SPORT_CATEGORY)[@sport_class.category.to_sym])%>
    <div>
      <p class="card-title"><%= @sport_class.category %></p>
      <div class="card-body">
        <h3 class="card-text" id="sport_class_name_show"><%= @sport_class.name %></h3>
        <h6 class="card-description-show"><em> <%= @sport_class.description %> </em></h5>
      </div>

      <div class="infos-show">
        <ul id="list-show">
          <li id="white_font"><i class="fas fa-user-friends"></i><%= @sport_class.group_size %> </li>
          <li id="white_font"><i class="fas fa-clock"></i><%= @sport_class.duration %> </li>
          <li id="white_font"><i class="fas fa-euro-sign"></i><%= @sport_class.price.to_i %> </li>
        </ul>
      </div>
       </div>

        <div class="button-show">
          <%= link_to "", edit_sport_class_path(@sport_class), class: "fas fa-pen" %>
          <%= link_to "", @sport_class, method: :delete, data: { confirm: "Are you sure?" }, class: "fas fa-trash" %>
        </div>
    </div>


  </div>
</div>