config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # get "fullcalendar", to: "pages#fullcalendar"
  get "calendar", to: "time_slots#calendar"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :time_slots, only: [:show, :index, :create, :update, :edit, :destroy] do
    resources :bookings, only: [:new, :create, :show]
    put :update_times, on: :member
  end

  resources :bookings, only: [:update]

  resources :users, only: [:user_profile] do
    resources :sport_classes, only: [:show, :new, :create, :index]
  end

  get "clients", to: "users#user_clients", as: "user_clients"
  get "clients/:id", to: "users#client_profile", as: "client_profile"

  resources :sport_classes
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>COACHEO</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Merriweather+Sans:wght@300;400;500;600&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <%

    url = "https://images.unsplash.com/photo-1518459031867-a89b944bffe4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2341&q=80"
    body_style = !devise_controller? ? '' : "background-blend-mode:luminosity;background-size: cover;background-position: center;background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(#{url});"
  %>

  <body style="<%= body_style %>">

<%#
    <div id="sidebar">
      <%= link_to root_path do %>
        <%# <h1>Coach'eo</h1>
      <% end %>
      <%# <% if current_user.present? %>
      <%# <ul class="nsidebar"> %>
        <%# <li> %>
        <%# <i class="fas fa-home"></i> <%= link_to "Tableau de bord", root_path%>
        <%# </li> %>
        <%# <li> %>
          <%# <i class="fas fa-calendar-week"></i> <%= link_to "Agenda", fullcalendar_path %>
        <%# </li> %>
        <%# <li> %>
          <%# <i class="fas fa-users"></i><%= link_to "Clients", user_clients_path  %>
        <%# </li> %>
        <%# <li> %>
          <%# <i class="fas fa-dumbbell"></i><%= link_to "Catalogue cours", sport_classes_path %>
        <%# </li> %>
      <%# </ul> %>
      <%# <% end %>
    <%# </div> %>


    <% if current_user %>
      <div id="sidebar">
        <div class="icone">
          <%= link_to root_path do %> <i class="fas fa-home"></i> <%end%>
          <%= link_to calendar_path do %> <i class="fas fa-calendar-week"></i> <%end%>
          <%= link_to user_clients_path do %> <i class="fas fa-users"></i> <%end%>
          <%= link_to sport_classes_path do%> <i class="fas fa-dumbbell"></i> <%end%>
        </div>
      </div>
    <% end %>




    <div class="main-container">
      <%= render 'shared/navbar' %>
      <div class="container">
        <%= render 'shared/flashes' %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>